# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute app to firebase App Distribution"
  lane :distribute do
      firebase_app_distribution(
       app: "1:704907043996:android:d9f445322b34d35b263959",
       firebase_cli_token: ENV["FIREBASE_TOKEN"],
       android_artifact_type: "APK",
       testers: "amr.reda2014@yahoo.com",
       release_notes: "New Flutter release uploaded with Fastlane",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk" )


  end
end
